/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import static game.SaveGame.g;
import java.awt.TextArea;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jadey
 */
public class GUI extends javax.swing.JFrame {

    

    
    Player pc;
    String name;

    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        this.setTitle("OZIRIS RISING!");
        initComponents();
        newGame.setVisible(false);
        loopPanel.setVisible(false);
        loadGame.setVisible(false);
        verifyLoad.setVisible(false);
        battle.setVisible(false);
        saveGame.setVisible(false);
        restartPanel.setVisible(false);


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        titleLabel = new java.awt.Label();
        newGameBtn = new javax.swing.JButton();
        loadGameBtn = new javax.swing.JButton();
        newGame = new javax.swing.JPanel();
        charaInputNew = new javax.swing.JPanel();
        enterCharacterName = new javax.swing.JLabel();
        charaNameInput = new javax.swing.JTextField();
        contBtnNew = new javax.swing.JButton();
        verifyNew = new javax.swing.JPanel();
        jScrollPaneNew = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        yesBtnNew = new javax.swing.JButton();
        noBtnNew = new javax.swing.JButton();
        battle = new javax.swing.JPanel();
        battleText = new java.awt.TextField();
        playerStats = new java.awt.Label();
        enemyStats = new java.awt.Label();
        fightBtn = new javax.swing.JButton();
        runBtn = new javax.swing.JButton();
        battleEndedContinueBtn = new javax.swing.JButton();
        loopPanel = new javax.swing.JPanel();
        continueBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        restartBtn = new javax.swing.JButton();
        characterInfo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        loadGame = new javax.swing.JPanel();
        charaInput = new javax.swing.JPanel();
        enterCharacterName1 = new javax.swing.JLabel();
        charaNameInput1 = new javax.swing.JTextField();
        contBtn1 = new javax.swing.JButton();
        verifyLoad = new javax.swing.JPanel();
        jScrollPaneLoad = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        yesBtnLoad = new javax.swing.JButton();
        noBtnLoad = new javax.swing.JButton();
        saveGame = new javax.swing.JPanel();
        saveLabel = new javax.swing.JLabel();
        saveText = new java.awt.TextArea();
        yesBtnSave = new javax.swing.JButton();
        noBtnSave = new javax.swing.JButton();
        contBtnSave = new javax.swing.JButton();
        restartPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        yesBtnSaveRestart = new javax.swing.JButton();
        noBtnRestartSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));

        titlePanel.setMinimumSize(new java.awt.Dimension(500, 500));

        TitlePanel.setMinimumSize(new java.awt.Dimension(500, 500));

        titleLabel.setAlignment(java.awt.Label.CENTER);
        titleLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titleLabel.setText("OZIRIS RISING");

        newGameBtn.setText("New Game");
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });

        loadGameBtn.setText("Load Game");
        loadGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TitlePanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loadGameBtn)
                            .addComponent(newGameBtn)))
                    .addGroup(TitlePanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(newGameBtn)
                .addGap(18, 18, 18)
                .addComponent(loadGameBtn)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        newGame.setMinimumSize(new java.awt.Dimension(500, 500));
        newGame.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                newGameComponentHidden(evt);
            }
        });

        charaInputNew.setMinimumSize(new java.awt.Dimension(500, 500));

        enterCharacterName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterCharacterName.setText("Enter Character Name");
        enterCharacterName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        charaNameInput.setText("Character Name Here");
        charaNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charaNameInputActionPerformed(evt);
            }
        });

        contBtnNew.setText("Continue");
        contBtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contBtnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout charaInputNewLayout = new javax.swing.GroupLayout(charaInputNew);
        charaInputNew.setLayout(charaInputNewLayout);
        charaInputNewLayout.setHorizontalGroup(
            charaInputNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charaInputNewLayout.createSequentialGroup()
                .addGroup(charaInputNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(charaInputNewLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(enterCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(charaInputNewLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(charaNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(charaInputNewLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(contBtnNew)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        charaInputNewLayout.setVerticalGroup(
            charaInputNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charaInputNewLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(enterCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(charaNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(contBtnNew)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        verifyNew.setMinimumSize(new java.awt.Dimension(500, 500));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("There is currently a save file for this name. \nWould you still like to use this name?");
        jScrollPaneNew.setViewportView(jTextArea2);

        yesBtnNew.setText("Yes");
        yesBtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnNewActionPerformed(evt);
            }
        });

        noBtnNew.setText("No");
        noBtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBtnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verifyNewLayout = new javax.swing.GroupLayout(verifyNew);
        verifyNew.setLayout(verifyNewLayout);
        verifyNewLayout.setHorizontalGroup(
            verifyNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verifyNewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yesBtnNew)
                .addGap(80, 80, 80)
                .addComponent(noBtnNew)
                .addGap(167, 167, 167))
            .addGroup(verifyNewLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPaneNew, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        verifyNewLayout.setVerticalGroup(
            verifyNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verifyNewLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jScrollPaneNew, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(verifyNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noBtnNew)
                    .addComponent(yesBtnNew))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout newGameLayout = new javax.swing.GroupLayout(newGame);
        newGame.setLayout(newGameLayout);
        newGameLayout.setHorizontalGroup(
            newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(charaInputNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(verifyNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        newGameLayout.setVerticalGroup(
            newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(charaInputNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(newGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(verifyNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        battle.setMinimumSize(new java.awt.Dimension(500, 500));

        battleText.setText("textField1");

        playerStats.setText("label1");

        enemyStats.setText("label1");

        fightBtn.setText("Fight");
        fightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightBtnActionPerformed(evt);
            }
        });

        runBtn.setText("Run");

        battleEndedContinueBtn.setLabel("Continue");
        battleEndedContinueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleEndedContinueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout battleLayout = new javax.swing.GroupLayout(battle);
        battle.setLayout(battleLayout);
        battleLayout.setHorizontalGroup(
            battleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battleLayout.createSequentialGroup()
                .addGroup(battleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(battleLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(battleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playerStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(battleText, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                            .addGroup(battleLayout.createSequentialGroup()
                                .addComponent(enemyStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104))))
                    .addGroup(battleLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(fightBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addGap(106, 106, 106)
                        .addComponent(runBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(battleEndedContinueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );

        battleLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fightBtn, runBtn});

        battleLayout.setVerticalGroup(
            battleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(playerStats, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(battleText, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enemyStats, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(battleEndedContinueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(battleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        battleLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fightBtn, runBtn});

        loopPanel.setMinimumSize(new java.awt.Dimension(500, 500));

        continueBtn.setText("Continue");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        restartBtn.setText("Restart");
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });

        characterInfo.setText("Name   HP:     XP: ");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane3.setViewportView(textArea);

        javax.swing.GroupLayout loopPanelLayout = new javax.swing.GroupLayout(loopPanel);
        loopPanel.setLayout(loopPanelLayout);
        loopPanelLayout.setHorizontalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loopPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(restartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loopPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        loopPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {continueBtn, restartBtn, saveBtn});

        loopPanelLayout.setVerticalGroup(
            loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addGroup(loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(loopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loopPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        loopPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {continueBtn, restartBtn, saveBtn});

        charaInput.setMinimumSize(new java.awt.Dimension(500, 500));

        enterCharacterName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterCharacterName1.setText("Enter Character Name");

        charaNameInput1.setText("Character Name Here");
        charaNameInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charaNameInput1ActionPerformed(evt);
            }
        });

        contBtn1.setText("Continue");
        contBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout charaInputLayout = new javax.swing.GroupLayout(charaInput);
        charaInput.setLayout(charaInputLayout);
        charaInputLayout.setHorizontalGroup(
            charaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charaInputLayout.createSequentialGroup()
                .addGroup(charaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(charaInputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enterCharacterName1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(charaInputLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(charaNameInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(charaInputLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(contBtn1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        charaInputLayout.setVerticalGroup(
            charaInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, charaInputLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(enterCharacterName1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(charaNameInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(contBtn1)
                .addGap(150, 150, 150))
        );

        verifyLoad.setMinimumSize(new java.awt.Dimension(500, 500));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("There is currently a save file for this name. \nWould you like to use this save?");
        jScrollPaneLoad.setViewportView(jTextArea1);

        yesBtnLoad.setText("Yes");
        yesBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnLoadActionPerformed(evt);
            }
        });

        noBtnLoad.setText("No");

        javax.swing.GroupLayout verifyLoadLayout = new javax.swing.GroupLayout(verifyLoad);
        verifyLoad.setLayout(verifyLoadLayout);
        verifyLoadLayout.setHorizontalGroup(
            verifyLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyLoadLayout.createSequentialGroup()
                .addGroup(verifyLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verifyLoadLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPaneLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verifyLoadLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(yesBtnLoad)
                        .addGap(65, 65, 65)
                        .addComponent(noBtnLoad)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        verifyLoadLayout.setVerticalGroup(
            verifyLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyLoadLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jScrollPaneLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(verifyLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBtnLoad)
                    .addComponent(noBtnLoad))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout loadGameLayout = new javax.swing.GroupLayout(loadGame);
        loadGame.setLayout(loadGameLayout);
        loadGameLayout.setHorizontalGroup(
            loadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(loadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loadGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(charaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(loadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loadGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(verifyLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        loadGameLayout.setVerticalGroup(
            loadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(loadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loadGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(charaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(loadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loadGameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(verifyLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        saveGame.setMinimumSize(new java.awt.Dimension(500, 500));

        saveLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        saveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveLabel.setText("Saving");

        saveText.setText("Do you want to save the game?");

        yesBtnSave.setText("Yes");
        yesBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnSaveActionPerformed(evt);
            }
        });

        noBtnSave.setText("No");

        contBtnSave.setText("Continue");
        contBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contBtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveGameLayout = new javax.swing.GroupLayout(saveGame);
        saveGame.setLayout(saveGameLayout);
        saveGameLayout.setHorizontalGroup(
            saveGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveGameLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(saveText, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveGameLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(yesBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noBtnSave)
                .addGap(73, 73, 73))
            .addGroup(saveGameLayout.createSequentialGroup()
                .addGroup(saveGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveGameLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(saveLabel))
                    .addGroup(saveGameLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(contBtnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveGameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {contBtnSave, noBtnSave, yesBtnSave});

        saveGameLayout.setVerticalGroup(
            saveGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveGameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(saveLabel)
                .addGap(19, 19, 19)
                .addComponent(saveText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(contBtnSave)
                .addGap(18, 18, 18)
                .addGroup(saveGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noBtnSave))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        saveGameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contBtnSave, noBtnSave, yesBtnSave});

        restartPanel.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Do you want to save current progress?");

        yesBtnSaveRestart.setText("Yes");
        yesBtnSaveRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnSaveRestartActionPerformed(evt);
            }
        });

        noBtnRestartSave.setText("No");
        noBtnRestartSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBtnRestartSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout restartPanelLayout = new javax.swing.GroupLayout(restartPanel);
        restartPanel.setLayout(restartPanelLayout);
        restartPanelLayout.setHorizontalGroup(
            restartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restartPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(restartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restartPanelLayout.createSequentialGroup()
                        .addComponent(yesBtnSaveRestart)
                        .addGap(88, 88, 88)
                        .addComponent(noBtnRestartSave))
                    .addComponent(jLabel1))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        restartPanelLayout.setVerticalGroup(
            restartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restartPanelLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addGap(141, 141, 141)
                .addGroup(restartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBtnSaveRestart)
                    .addComponent(noBtnRestartSave))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(battle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(newGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loadGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saveGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(restartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(battle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(newGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loadGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(saveGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(restartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBtnActionPerformed
        // TODO add your handling code here:
        titlePanel.setVisible(false);
        newGame.setVisible(true);
//        enterCharacterName.setVisible(true);
    }//GEN-LAST:event_newGameBtnActionPerformed

    private void newGameComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newGameComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_newGameComponentHidden

    private void charaNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charaNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charaNameInputActionPerformed

    private void contBtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contBtnNewActionPerformed
        //get name from text area          
        name = charaNameInput.getText();
        try {
            if(Player.ifPlayerExists(name))
            {
                newGame.setVisible(false);
                verifyLoad.setVisible(true);
            } else 
            {
                GameLogic.setPlayer(name);
                newGame.setVisible(false);
                setLoopPanel();           
                loopPanel.setVisible(true);
                
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

       
       
    }//GEN-LAST:event_contBtnNewActionPerformed

    private void charaNameInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charaNameInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charaNameInput1ActionPerformed

    private void contBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contBtn1ActionPerformed
        
        name = charaNameInput1.getText();
        try {
            if(!Player.ifPlayerExists(name)){
                
                GameLogic.setPlayer(name);

            }
            else{
                confirmLoad();
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        };
        pc = GameLogic.player;
        loadGame.setVisible(false);
        setLoopPanel();
        loopPanel.setVisible(true);

    }//GEN-LAST:event_contBtn1ActionPerformed

    private void loadGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameBtnActionPerformed
        // TODO add your handling code here:
        titlePanel.setVisible(false);
        loadGame.setVisible(true);
    }//GEN-LAST:event_loadGameBtnActionPerformed

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
        // move to restart panel
        loopPanel.setVisible(false);
        restartPanel.setVisible(true);

    }//GEN-LAST:event_restartBtnActionPerformed

    private void yesBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnLoadActionPerformed
        try {
            newGame.setVisible(false);
            pc = LoadGame.loadSave(name);
            GameLogic.player = pc;
//        updatePc();
        } catch (SQLException ex) {   
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        verifyLoad.setVisible(false);
        setLoopPanel();
        loopPanel.setVisible(true);
   
    }//GEN-LAST:event_yesBtnLoadActionPerformed

    private void yesBtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnNewActionPerformed
        try {
            String name = charaNameInput.getText();
            GameLogic.setPlayer(name);
            
            //start with intro
            String text = "You are a brave hero who has been captured by the evil emperor Gnosis! \n" +
                    "Thrown into the dungeon of his castle to rot, you plot an escape.\n" +
                    "One day, a large explosion rock the castle, rubble falling into your chamber. \n" +
                    "The force has knocked loose the cage door from the stone!\n" +
                    "This is your chance!\n" +
                    "Onward brave hero!";
            String charaInfo = "Name:        " + GameLogic.player.name +"    HP:      " + GameLogic.player.hp + "     XP:         " + GameLogic.player.xp;
            textArea.setText(text);
            textArea.setEditable(false);
            loopPanel.setVisible(true);
            
            characterInfo.setText(charaInfo);
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            }//GEN-LAST:event_yesBtnNewActionPerformed

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
       setLoopPanel();
        GameLogic.continueAdventure();
        
    }//GEN-LAST:event_continueBtnActionPerformed

    private void noBtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBtnNewActionPerformed
        // return to name panel
        verifyNew.setVisible(false);
        charaInputNew.setVisible(true);
    }//GEN-LAST:event_noBtnNewActionPerformed

    private void fightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightBtnActionPerformed
        Battle.fight();
    }//GEN-LAST:event_fightBtnActionPerformed

    private void battleEndedContinueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleEndedContinueBtnActionPerformed
        //move to loop panel
        battle.setVisible(false);
        setLoopPanel();
        loopPanel.setVisible(true);
    }//GEN-LAST:event_battleEndedContinueBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
       //move to save panel
        loopPanel.setVisible(false);
       saveGame.setVisible(true);
       contBtnSave.setVisible(false);
       saveText.setVisible(true);
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void yesBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnSaveActionPerformed
        try {
            if((Player.ifPlayerExists(name))){
                String overwrite = "You have an existing save. Overwrite it?";
                saveText.setText(overwrite);
                yesBtnSave.setVisible(true);
                noBtnSave.setVisible(true);
            }
            else{
                SaveGame.saveGame(GameLogic.player);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
         yesBtnSave.setVisible(false);
        noBtnSave.setVisible(false);
    }//GEN-LAST:event_yesBtnSaveActionPerformed

    private void contBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contBtnSaveActionPerformed
        // return to loop
        saveGame.setVisible(false);
        loopPanel.setVisible(true);
        
        
        
    }//GEN-LAST:event_contBtnSaveActionPerformed

    private void yesBtnSaveRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnSaveRestartActionPerformed
        //move to save Panel
        restartPanel.setVisible(false);
        saveGame.setVisible(true);
        contBtnSave.setVisible(false);
          yesBtnSave.setVisible(true);
        noBtnSave.setVisible(true);
        

    }//GEN-LAST:event_yesBtnSaveRestartActionPerformed

    private void noBtnRestartSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBtnRestartSaveActionPerformed
        // move to titlePanel
        restartPanel.setVisible(false);
        titlePanel.setVisible(true);
    }//GEN-LAST:event_noBtnRestartSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JPanel battle;
    protected javax.swing.JButton battleEndedContinueBtn;
    protected java.awt.TextField battleText;
    private javax.swing.JPanel charaInput;
    private javax.swing.JPanel charaInputNew;
    private javax.swing.JTextField charaNameInput;
    private javax.swing.JTextField charaNameInput1;
    private javax.swing.JLabel characterInfo;
    private javax.swing.JButton contBtn1;
    private javax.swing.JButton contBtnNew;
    private javax.swing.JButton contBtnSave;
    private javax.swing.JButton continueBtn;
    protected java.awt.Label enemyStats;
    private javax.swing.JLabel enterCharacterName;
    private javax.swing.JLabel enterCharacterName1;
    protected javax.swing.JButton fightBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneLoad;
    private javax.swing.JScrollPane jScrollPaneNew;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel loadGame;
    private javax.swing.JButton loadGameBtn;
    private javax.swing.JPanel loopPanel;
    private javax.swing.JPanel newGame;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JButton noBtnLoad;
    private javax.swing.JButton noBtnNew;
    private javax.swing.JButton noBtnRestartSave;
    protected javax.swing.JButton noBtnSave;
    protected java.awt.Label playerStats;
    private javax.swing.JButton restartBtn;
    private javax.swing.JPanel restartPanel;
    protected javax.swing.JButton runBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel saveGame;
    private javax.swing.JLabel saveLabel;
    protected java.awt.TextArea saveText;
    protected javax.swing.JTextArea textArea;
    private java.awt.Label titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel verifyLoad;
    private javax.swing.JPanel verifyNew;
    private javax.swing.JButton yesBtnLoad;
    private javax.swing.JButton yesBtnNew;
    protected javax.swing.JButton yesBtnSave;
    private javax.swing.JButton yesBtnSaveRestart;
    // End of variables declaration//GEN-END:variables

    private void confirmLoad() {
        charaInput.setVisible(false);
        verifyLoad.setVisible(true);
    }
    
//    public void updatePc(){
//      pc = GameLogic.player;
//    }

    private void setLoopPanel() {
//        updatePc();
        int roomNo = GameLogic.player.roomCount;
        String t;
        if(roomNo == 0){
            t = "You are a brave hero who has been captured by the evil emperor Gnosis! \n" +
            "Thrown into the dungeon of his castle to rot, you plot an escape.\n" +
            "One day, a large explosion rock the castle, rubble falling into your chamber. \n" +
            "The force has knocked loose the cage door from the stone!\n" +
            "This is your chance!\n" +
            "Onward brave hero!";
        }else{
        t = Map.getRoomDesc(roomNo);
        }
        textArea.setText(t);
        String l = "Name: " + GameLogic.player.name + "     HP: " + GameLogic.player.hp +"      XP: " + GameLogic.player.xp;
        characterInfo.setText(l);
    }
    
    public void battleStart() {
        loopPanel.setVisible(false);
        battle.setVisible(true);
        battleEndedContinueBtn.setVisible(false);
    }
    
    static void bossBattle() {
        String bossIntro = "This is it.\n";
       
            System.out.println("The final battle");
            anyKeyToContinue();
            System.out.println("(1) Yes! Bring it on!");
            System.out.println("(2)NO! TAKE ME HOME!");
            int input = getInput("->", 2);
            if(input == 2){
                clearConsole();
                System.out.println("Silly " + player.getName() + ", you're the hero.");
                anyKeyToContinue();
                clearConsole();
                System.out.println("You don't get a choice!");
                anyKeyToContinue();

            }
            clearConsole();
            System.out.println(Map.getRoomDesc(player.roomCount));
            anyKeyToContinue();
            Battle.finalBattle(player);
            System.out.println("Thank you for Playing!");
                    isRunning = false;

    }

   

}




